[package]
name = "restd"
version = "0.1.0"
edition = "2018"

[dependencies]

[lib]
path = "lib.rs"
crate-type = ["staticlib", "rlib"]

[features]
# Treat warnings as a build error on Travis.
strict = []
